<a href="https://colab.research.google.com/github/Durgaprasad-77/Heart-Attack-Chance-Prediction/blob/main/Heart_Attack_Chance_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing necessary Lib

In [18]:
import pandas as pd 
import numpy as np
from  sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('/content/drive/MyDrive/heart.csv')

In [5]:
data.head()

age  sex  cp  trtbps  chol  fbs  ...  exng  oldpeak  slp  caa  thall  output
0   63    1   3     145   233    1  ...     0      2.3    0    0      1       1
1   37    1   2     130   250    0  ...     0      3.5    0    0      2       1
2   41    0   1     130   204    0  ...     0      1.4    2    0      2       1
3   56    1   1     120   236    0  ...     0      0.8    2    0      2       1
4   57    0   0     120   354    0  ...     1      0.6    2    0      2       1

[5 rows x 14 columns]

Checking If there are any Null values

In [16]:
data.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [13]:
data.describe

<bound method NDFrame.describe of      age  sex  cp  trtbps  chol  fbs  ...  exng  oldpeak  slp  caa  thall  output
0     63    1   3     145   233    1  ...     0      2.3    0    0      1       1
1     37    1   2     130   250    0  ...     0      3.5    0    0      2       1
2     41    0   1     130   204    0  ...     0      1.4    2    0      2       1
3     56    1   1     120   236    0  ...     0      0.8    2    0      2       1
4     57    0   0     120   354    0  ...     1      0.6    2    0      2       1
..   ...  ...  ..     ...   ...  ...  ...   ...      ...  ...  ...    ...     ...
298   57    0   0     140   241    0  ...     1      0.2    1    0      3       0
299   45    1   3     110   264    0  ...     0      1.2    1    0      3       0
300   68    1   0     144   193    1  ...     0      3.4    1    2      3       0
301   57    1   0     130   131    0  ...     1      1.2    1    1      3       0
302   57    0   1     130   236    0  ...     0      0.0    1   

Defining Training and Testing

In [17]:
X = data.drop(columns = ['output'])
y = data.output

In [20]:
x_train,x_test,y_train,y_test =  train_test_split(X,y,random_state = 1)

In [21]:
x_train

age  sex  cp  trtbps  chol  fbs  ...  thalachh  exng  oldpeak  slp  caa  thall
170   56    1   2     130   256    1  ...       142     1      0.6    1    1      1
192   54    1   0     120   188    0  ...       113     0      1.4    1    1      3
168   63    1   0     130   254    0  ...       147     0      1.4    1    1      3
42    45    1   0     104   208    0  ...       148     1      3.0    1    0      2
90    48    1   2     124   255    1  ...       175     0      0.0    2    2      2
..   ...  ...  ..     ...   ...  ...  ...       ...   ...      ...  ...  ...    ...
203   68    1   2     180   274    1  ...       150     1      1.6    1    0      3
255   45    1   0     142   309    0  ...       147     1      0.0    1    3      3
72    29    1   1     130   204    0  ...       202     0      0.0    2    0      2
235   51    1   0     140   299    0  ...       173     1      1.6    2    0      3
37    54    1   2     150   232    0  ...       165     0      1.6    2    0      3

[227 rows x 13 columns]

Bring in Logistical Regression and Fit in our train sets

In [ ]:
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)

In [26]:
y_pred = log_reg.predict(x_test)

In [27]:
confusion_matrix(y_test,y_pred)

array([[24, 11],
       [ 5, 36]])

In [28]:
from sklearn.metrics import accuracy_score

Accuracy Test score

In [29]:
accuracy_score(y_test,y_pred)

0.7894736842105263

In [30]:
x_test.head()

age  sex  cp  trtbps  chol  fbs  ...  thalachh  exng  oldpeak  slp  caa  thall
204   62    0   0     160   164    0  ...       145     0      6.2    0    3      3
159   56    1   1     130   221    0  ...       163     0      0.0    2    0      3
219   48    1   0     130   256    1  ...       150     1      0.0    2    2      3
174   60    1   0     130   206    0  ...       132     1      2.4    1    2      3
184   50    1   0     150   243    0  ...       128     0      2.6    1    0      3

[5 rows x 13 columns]

Finally Predicting the Chances of Heart Attack by random values

In [34]:
log_reg.predict([[25,1,0,120,230,1,0,140,0,2,2.5,0,3]])

array([0])

Predicitng the Probability 


In [35]:
log_reg.predict_proba([[25,1,0,120,230,1,0,140,0,2,2.5,0,3]])

array([[0.85634028, 0.14365972]])